"""Delegation lifecycle, ledger, and backend registry for agency-runtime."""

from agency_runtime.core.delegation.backends import (
    BackendError,
    BackendExecutionError,
    BackendProtocolError,
    BackendRegistry,
    BackendTimeoutError,
    BackendUnavailableError,
    ClaudeExecBackend,
    CodexExecBackend,
    CommandBackend,
    DEFAULT_REGISTRY,
    DelegateBackend,
    GenericCLIBackend,
    HermesDelegateBackend,
    OpenClawAgentBackend,
    OpenClawSessionsBackend,
    get_delegate_func,
    register_backend,
)
from agency_runtime.core.delegation.ledger import DelegationLedger, DelegationLedgerEntry
from agency_runtime.core.delegation.lifecycle import (
    DEFAULT_MAX_WORKERS,
    DEFAULT_WORKTREE_ROOT,
    DependencyGraph,
    LifecycleResult,
    WorkUnit,
    WorktreeInfo,
    aggregate_results,
    build_dependency_graph,
    cleanup_worktrees,
    delegate_with_lifecycle,
    dispatch_work_units,
    normalize_work_units,
    provision_worktrees,
)

__all__ = [
    "BackendError",
    "BackendExecutionError",
    "BackendProtocolError",
    "BackendRegistry",
    "BackendTimeoutError",
    "BackendUnavailableError",
    "ClaudeExecBackend",
    "CodexExecBackend",
    "CommandBackend",
    "DEFAULT_REGISTRY",
    "DEFAULT_MAX_WORKERS",
    "DEFAULT_WORKTREE_ROOT",
    "DelegateBackend",
    "DelegationLedger",
    "DelegationLedgerEntry",
    "DependencyGraph",
    "GenericCLIBackend",
    "HermesDelegateBackend",
    "LifecycleResult",
    "OpenClawAgentBackend",
    "OpenClawSessionsBackend",
    "WorkUnit",
    "WorktreeInfo",
    "aggregate_results",
    "build_dependency_graph",
    "cleanup_worktrees",
    "delegate_with_lifecycle",
    "dispatch_work_units",
    "get_delegate_func",
    "normalize_work_units",
    "provision_worktrees",
    "register_backend",
]
