"""Security-reviewed Agency-owned contractor contracts required by AR-122."""

from __future__ import annotations

from typing import Any

from agency_runtime.core.workforce.hiring_contract import (
    EmploymentContract,
    parse_employment_contract,
)

_HOSTS = ["codex", "claude", "openclaw", "hermes", "zcode"]
_PLATFORMS = ["windows", "linux"]


def _definition(
    slug: str,
    role: str,
    scope: str,
    *,
    outcomes: list[str],
    artifacts: list[str],
    capabilities: list[str],
    anti: list[str],
    phases: list[str],
    tools: list[str],
    evidence: list[str] | None = None,
    closest: str,
    insufficiency: str,
    differentiation: str,
    positive: str,
    negative: str,
    negative_rationale: str,
    authority: str = "modify",
    relationship: str = "complements",
    relationship_target: str | None = None,
) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "slug": slug,
        "role": role,
        "narrow_scope": scope,
        "outcomes_owned": outcomes,
        "artifacts_produced": artifacts,
        "capabilities": capabilities,
        "anti_capabilities": anti,
        "preferred_scenarios": [positive],
        "avoided_scenarios": [negative],
        "forbidden_scenarios": [f"Act outside {scope.casefold()}"],
        "lifecycle_phases": phases,
        "authority": authority,
        "context_mode": "isolated_only",
        "external_mutation": False,
        "tools": tools,
        "platforms": _PLATFORMS,
        "hosts": _HOSTS,
        "requirements": ["Receive a bounded work unit and repository policy"],
        "relationships": (
            [{"kind": relationship, "target": relationship_target}] if relationship_target else []
        ),
        "evidence_requirements": evidence or ["Changed artifacts and focused verification results"],
        "closest_workers": [
            {
                "worker": closest,
                "insufficiency": insufficiency,
                "differentiation": differentiation,
            }
        ],
        "positive_evaluations": [
            {
                "case_id": f"positive-{slug}",
                "scenario": positive,
                "expectation": "select",
                "rationale": differentiation,
            }
        ],
        "hard_negative_evaluations": [
            {
                "case_id": f"negative-{slug}",
                "scenario": negative,
                "expectation": "select_other",
                "rationale": negative_rationale,
            }
        ],
    }


_RAW_DEFINITIONS = (
    _definition(
        "python-application-engineer",
        "Python Application Engineer",
        "Production Python applications, services, and CLIs",
        outcomes=["Maintainable production Python behavior", "Portable Python packaging"],
        artifacts=["Python source", "Python package configuration"],
        capabilities=["Async Python design", "Typing and tests", "CLI and service packaging"],
        anti=["Machine-learning model design", "Data-science analysis", "Visual frontend design"],
        phases=["implementation", "testing"],
        tools=["repository", "python", "test-runner", "package-manager"],
        closest="rapid-prototyper",
        insufficiency="Optimizes for prototypes rather than production Python maintainability and packaging",
        differentiation="Owns production Python application engineering without absorbing ML or data specialties",
        positive="Build a typed async Python CLI with packaging and failure-path tests",
        negative="Train and evaluate a specialized machine-learning model",
        negative_rationale="A machine-learning specialist owns model development",
        relationship_target="software-test-engineer",
    ),
    _definition(
        "typescript-application-engineer",
        "TypeScript Application Engineer",
        "Node.js services, CLIs, packages, and libraries",
        outcomes=["Type-safe Node.js runtime behavior", "Portable TypeScript packages"],
        artifacts=["TypeScript source", "Node.js build configuration"],
        capabilities=[
            "Type-system design",
            "Async Node.js behavior",
            "Runtime validation",
            "Build and test tooling",
        ],
        anti=["Visual frontend design", "Brand design", "User-interface art direction"],
        phases=["implementation", "testing"],
        tools=["repository", "node", "test-runner", "package-manager"],
        closest="frontend-developer",
        insufficiency="Owns browser presentation rather than general Node.js services, CLIs, and libraries",
        differentiation="Owns nonvisual TypeScript application and package engineering",
        positive="Build a cross-platform TypeScript CLI with runtime validation and async tests",
        negative="Design and implement a polished responsive marketing interface",
        negative_rationale="A visual frontend specialist owns interface implementation",
        relationship_target="software-test-engineer",
    ),
    _definition(
        "backend-service-engineer",
        "Backend Service Engineer",
        "Language-independent backend service implementation concerns",
        outcomes=["Reliable service boundaries", "Operable request and persistence behavior"],
        artifacts=["Service implementation", "Service configuration"],
        capabilities=[
            "API execution paths",
            "Persistence integration",
            "Concurrency and failure handling",
            "Input validation and contract-safe outputs",
            "Authentication and authorization enforcement",
            "Idempotency, retry, and rollback behavior",
        ],
        anti=[
            "Architecture-only recommendations",
            "Language-specific craftsmanship",
            "Visual frontend design",
        ],
        phases=["implementation", "integration"],
        tools=["repository", "shell", "test-runner"],
        evidence=[
            "Changed backend path and behavior summary",
            "One critical success-path and one high-risk failure-path receipt",
            "Persistence, rollback, and authorization evidence for changed write paths",
        ],
        closest="backend-architect",
        insufficiency="Defines backend architecture but does not own implementation execution",
        differentiation="Implements language-independent service seams while language specialists own syntax-level craft",
        positive="Implement retries, idempotency, persistence, and error handling across a backend service",
        negative="Choose an enterprise-wide target architecture without implementing a service",
        negative_rationale="An architecture specialist owns architecture-only decisions",
        relationship_target="software-test-engineer",
    ),
    _definition(
        "software-test-engineer",
        "Software Test Engineer",
        "Implementation of software test suites and failure-path harnesses",
        outcomes=["Meaningful executable test coverage", "Reproducible failure detection"],
        artifacts=["Unit and integration tests", "Contract and property tests"],
        capabilities=[
            "Unit tests",
            "Integration tests",
            "Contract tests",
            "Property tests",
            "Concurrency and failure-path tests",
        ],
        anti=[
            "Test-result interpretation",
            "Release certification",
            "Production completion claims",
        ],
        phases=["testing"],
        tools=["repository", "test-runner"],
        closest="test-automation-engineer",
        insufficiency="Focuses automation infrastructure rather than broad code-level test implementation",
        differentiation="Implements multiple test forms without interpreting completed evidence or certifying release",
        positive="Add property, concurrency, contract, and failure-path tests to an existing service",
        negative="Interpret a completed flaky test report and decide whether the product can ship",
        negative_rationale="Result analysis and release verification require independent specialists",
        relationship_target="application-integration-verifier",
    ),
    _definition(
        "cross-platform-installer-engineer",
        "Cross-Platform Installer Engineer",
        "Windows and Linux installation, upgrade, uninstall, and configuration flows",
        outcomes=[
            "Repeatable Windows and Linux installation",
            "Recoverable upgrade and uninstall behavior",
        ],
        artifacts=["Installer implementation", "Installation configuration"],
        capabilities=[
            "Platform path handling",
            "Service registration",
            "Upgrade and rollback",
            "Unattended installation",
        ],
        anti=[
            "Application feature implementation",
            "Release certification",
            "Operating-system kernel development",
        ],
        phases=["implementation", "installation"],
        tools=["repository", "shell", "package-manager"],
        closest="devops-automator",
        insufficiency="Automates delivery infrastructure rather than end-user Windows and Linux installers",
        differentiation="Owns local installed-product lifecycle across supported operating systems",
        positive="Implement idempotent Windows and Linux install, upgrade, rollback, and uninstall flows",
        negative="Design a cloud deployment pipeline for an already packaged service",
        negative_rationale="A delivery automation specialist owns cloud pipeline work",
        relationship_target="cross-platform-release-verifier",
    ),
    _definition(
        "application-observability-engineer",
        "Application Observability Engineer",
        "Runtime telemetry, diagnostics, health, and failure-recovery visibility",
        outcomes=["Actionable runtime telemetry", "Diagnosable application failures"],
        artifacts=["Metrics and tracing instrumentation", "Health and diagnostic configuration"],
        capabilities=[
            "Structured logging",
            "Metrics",
            "Distributed tracing",
            "Health signals",
            "Failure diagnostics",
        ],
        anti=[
            "Business analytics",
            "Performance optimization without measurement",
            "Infrastructure ownership",
        ],
        phases=["implementation", "observability"],
        tools=["repository", "monitoring", "test-runner"],
        closest="performance-benchmarker",
        insufficiency="Measures performance but does not own production telemetry and diagnostics",
        differentiation="Builds application-level visibility while benchmarking remains independent",
        positive="Instrument a service with traces, metrics, health signals, and failure diagnostics",
        negative="Benchmark and optimize a CPU-bound algorithm against a latency target",
        negative_rationale="A performance specialist owns measurement-led optimization",
        relationship_target="application-integration-verifier",
    ),
    _definition(
        "application-integration-verifier",
        "Application Integration Verifier",
        "Independent verification of seams across complete application artifacts",
        outcomes=["Verified cross-component workflows", "Documented integration failures"],
        artifacts=["Integration verification report", "Cross-component evidence"],
        capabilities=[
            "UI and API seam validation",
            "Authentication and data-flow validation",
            "Configuration and installation seam validation",
        ],
        anti=["Feature implementation", "Unit-test authorship", "Release certification"],
        phases=["integration", "review"],
        tools=["artifact-reader", "test-runner", "browser"],
        closest="reality-checker",
        insufficiency="Challenges claims broadly but does not systematically verify application seams",
        differentiation="Independently evaluates UI, API, authentication, data, configuration, installation, tests, and documentation together",
        positive="Verify an installed app from login through API, persistence, configuration, and documented recovery",
        negative="Implement the missing authentication endpoint found during verification",
        negative_rationale="An implementation specialist must repair the defect before independent re-verification",
        authority="review",
        relationship_target="software-test-engineer",
    ),
    _definition(
        "ai-evaluation-engineer",
        "AI Evaluation Engineer",
        "Evaluation design for prompts, retrieval, tools, and multi-step AI workflows",
        outcomes=[
            "Decision-grade AI quality measurement",
            "Regression thresholds tied to real workflow failures",
        ],
        artifacts=[
            "Prioritized evaluation scenario matrix",
            "Scoring rubric, thresholds, and limitations report",
        ],
        capabilities=[
            "Failure-mode-driven scenario design",
            "Prompt, retrieval, tool-use, and multi-turn evaluation",
            "Human-review and judgment-consistency design",
            "Quality, cost, and latency tradeoff measurement",
        ],
        anti=[
            "Vanity benchmarking",
            "Release claims from narrow happy-path samples",
            "Treating malformed or timed-out evaluations as valid losses",
        ],
        phases=["testing", "review"],
        tools=["artifact-reader", "test-runner"],
        evidence=[
            "Scenario-to-real-failure traceability",
            "Explicit scoring rubric, thresholds, and judgment method",
            "Dataset, evaluator, runtime, cost, latency, and live-validation limitations",
        ],
        closest="model-qa-specialist",
        insufficiency="Checks model outputs but does not own workflow-level measurement design and go or no-go thresholds",
        differentiation="Designs decision-grade evaluations across prompts, retrieval, tools, and multi-step workflows",
        positive="Design a regression evaluation for a retrieval-and-tool agent with quality, latency, and cost gates",
        negative="Implement production tracing and logging across the live AI request path",
        negative_rationale="An AI observability specialist owns production telemetry implementation and design",
        authority="review",
        relationship_target="ai-observability-engineer",
    ),
    _definition(
        "ai-observability-engineer",
        "AI Observability Engineer",
        "AI-native telemetry for prompts, context assembly, model calls, tools, and validated outputs",
        outcomes=[
            "Traceable probabilistic workflow execution",
            "Privacy-bounded AI failure diagnostics",
        ],
        artifacts=[
            "AI telemetry model and signal inventory",
            "Debugging, alerting, privacy, and residual-blind-spot report",
        ],
        capabilities=[
            "End-to-end AI execution tracing",
            "Quality, latency, cost, refusal, fallback, and error metrics",
            "Prompt, context, tool, and decision breadcrumb design",
            "Redaction, sampling, retention, and correlation boundaries",
        ],
        anti=[
            "Indiscriminate full-payload logging",
            "Business analytics ownership",
            "Claims that telemetry replaces evaluation coverage",
        ],
        phases=["observability", "planning"],
        tools=["artifact-reader", "monitoring"],
        evidence=[
            "Every recommended signal maps to a concrete debugging or governance question",
            "Sensitive-data minimization, redaction, sampling, and retention decisions",
            "Cost tradeoffs and residual blind spots requiring evaluation coverage",
        ],
        closest="application-observability-engineer",
        insufficiency="Owns conventional application telemetry but not probabilistic prompts, context, model, tool, and quality traces",
        differentiation="Specializes observability for AI execution paths and joins quality signals to operational traces",
        positive="Design traces and metrics that explain failures across retrieval, prompts, model calls, tools, and output validation",
        negative="Instrument a conventional service health endpoint and database latency dashboard with no AI workflow",
        negative_rationale="The application observability specialist owns conventional runtime telemetry",
        authority="plan",
        relationship_target="ai-evaluation-engineer",
    ),
    _definition(
        "documentation-evidence-researcher",
        "Documentation Evidence Researcher",
        "Primary-documentation verification of APIs, versions, defaults, caveats, and framework behavior",
        outcomes=[
            "Source-backed technical answers",
            "Explicit version, default, caveat, and uncertainty boundaries",
        ],
        artifacts=[
            "Citation-backed documentation research brief",
            "Ambiguity and runtime-validation checklist",
        ],
        capabilities=[
            "Primary-source documentation research",
            "Version and deprecation comparison",
            "API defaults, error modes, and caveat verification",
            "Fact, inference, and unresolved ambiguity separation",
        ],
        anti=[
            "Code implementation",
            "Uncited API claims",
            "Guessing when documentation is inconclusive",
        ],
        phases=["discovery", "documentation", "review"],
        tools=["artifact-reader", "web-research"],
        evidence=[
            "Exact primary references for every high-impact claim",
            "Target version, defaults, caveats, and deprecation context",
            "Confidence, unresolved ambiguity, and recommended runtime validation",
        ],
        closest="technical-writer",
        insufficiency="Authors technical prose but does not independently verify volatile API and framework contracts from primary documentation",
        differentiation="Researches and cites source-of-truth behavior while leaving documentation mutation to a writer",
        positive="Verify a framework API default and migration behavior for exact versions using primary documentation",
        negative="Rewrite the repository README and contributor guide after an implementation change",
        negative_rationale="A technical writer owns documentation mutation",
        authority="review",
    ),
    _definition(
        "hallucination-root-cause-investigator",
        "Hallucination Root-Cause Investigator",
        "Root-cause analysis of unsupported AI claims across context, retrieval, prompts, tools, and workflow design",
        outcomes=[
            "Evidence-backed factuality failure reconstruction",
            "Targeted recurrence reduction and regression cases",
        ],
        artifacts=[
            "Failure-path reconstruction and root-cause report",
            "Targeted fix, detection, and regression-case proposal",
        ],
        capabilities=[
            "Available-evidence reconstruction",
            "Retrieval, ranking, staleness, prompt, and tool-failure diagnosis",
            "Unsupported-inference and uncertainty-boundary analysis",
            "Root-cause-specific regression design",
        ],
        anti=[
            "Generic speculation without a failing path",
            "Calling every wrong answer a hallucination",
            "Wording-only suppression that leaves the root cause intact",
        ],
        phases=["discovery", "testing", "review"],
        tools=["artifact-reader", "test-runner"],
        evidence=[
            "Exact failing example and evidence available at each execution boundary",
            "Separation of missing evidence, ignored evidence, stale data, retrieval failure, and tool failure",
            "At least one targeted regression case and residual-risk statement",
        ],
        closest="reality-checker",
        insufficiency="Challenges claims broadly but does not reconstruct AI context, retrieval, prompt, and tool failure paths",
        differentiation="Diagnoses unsupported AI claims from the exact execution evidence and proposes root-cause-specific verification",
        positive="Investigate an unsupported answer by reconstructing retrieved context, prompt framing, tool results, and output validation",
        negative="Review a general product claim for plausibility when no AI factuality failure occurred",
        negative_rationale="A general evidence critic owns broad claim review",
        authority="review",
        relationship_target="ai-evaluation-engineer",
    ),
    _definition(
        "ai-governance-auditor",
        "AI Governance Auditor",
        "Operational AI governance review of controls, accountability, oversight, change management, and deployment readiness",
        outcomes=[
            "Concrete AI control-gap assessment",
            "Evidence-bounded deployment-readiness verdict",
        ],
        artifacts=[
            "AI system boundary and governance-gap audit",
            "Prioritized controls, missing evidence, and residual-risk report",
        ],
        capabilities=[
            "AI accountability and risk-ownership review",
            "Access, auditability, approval, and escalation control assessment",
            "Prompt, tool, model, and data-source change-governance review",
            "Deployment evidence and oversight readiness assessment",
        ],
        anti=[
            "Inventing regulatory requirements",
            "Generic policy commentary detached from system behavior",
            "Treating missing documents as proof that controls do not exist",
        ],
        phases=["review", "release"],
        tools=["artifact-reader"],
        evidence=[
            "Every concern maps to a concrete system behavior, control, owner, or workflow",
            "Confirmed gaps are separated from missing evidence and assumptions",
            "Impact, likelihood, implementable remediation, and residual risk",
        ],
        closest="compliance-auditor",
        insufficiency="Reviews general compliance but does not specialize in probabilistic model, prompt, tool, data, and oversight controls",
        differentiation="Audits operational governance for AI system boundaries without inventing organization-specific obligations",
        positive="Audit an agent system for ownership, approval, logging, change control, escalation, and deployment readiness",
        negative="Determine whether a financial filing complies with a named jurisdiction's current regulations",
        negative_rationale="A domain compliance specialist owns jurisdiction-specific regulatory review",
        authority="review",
        relationship_target="policy-guardrail-architect",
    ),
    _definition(
        "policy-guardrail-architect",
        "Policy Guardrail Architect",
        "Layered prompt, tool, workflow, validation, approval, and fallback guardrails for AI systems",
        outcomes=[
            "Enforceable risk-specific guardrail architecture",
            "Useful safe fallback and escalation behavior",
        ],
        artifacts=[
            "Layered guardrail architecture and failure-path map",
            "Tradeoff, test, bypass, and residual-risk plan",
        ],
        capabilities=[
            "Prevention, detection, confirmation, and fallback control design",
            "Tool allowlist, argument validation, and approval-boundary design",
            "Structured output, refusal, and low-confidence fallback design",
            "Guardrail false-positive, false-negative, latency, and usability analysis",
        ],
        anti=[
            "Prompt-only controls for high-impact actions",
            "Blanket blocking when scoped controls preserve usefulness",
            "Guardrails without failure-path tests or bypass analysis",
        ],
        phases=["planning", "design", "review"],
        tools=["artifact-reader"],
        evidence=[
            "Every guardrail maps to a specific failure path and enforcement layer",
            "Tests or evaluations for prevention, detection, confirmation, and fallback behavior",
            "Usability, latency, bypass, false-positive, false-negative, and residual-risk analysis",
        ],
        closest="security-architect",
        insufficiency="Designs broad system security but does not specialize in probabilistic prompt, tool, output, approval, and fallback controls",
        differentiation="Designs layered AI workflow guardrails that contain specific failures while preserving bounded usefulness",
        positive="Design layered controls for risky AI tool calls with validation, scoped approval, safe fallback, and bypass tests",
        negative="Perform a broad network and identity security architecture review for a non-AI service",
        negative_rationale="A security architect owns general system security architecture",
        authority="plan",
        relationship_target="ai-governance-auditor",
    ),
    _definition(
        "cross-platform-release-verifier",
        "Cross-Platform Release Verifier",
        "Independent installed-artifact release verification on Windows and Linux",
        outcomes=["Evidence-backed release readiness", "Verified installed-product portability"],
        artifacts=["Windows release evidence", "Linux release evidence", "Release verdict"],
        capabilities=[
            "Installed-artifact smoke testing",
            "Cross-platform configuration validation",
            "Upgrade and uninstall verification",
        ],
        anti=["Installer implementation", "Feature implementation", "CI-only release claims"],
        phases=["installation", "release"],
        tools=["artifact-reader", "shell", "test-runner"],
        closest="mobile-release-engineer",
        insufficiency="Owns mobile-store release concerns rather than Windows and Linux installed artifacts",
        differentiation="Requires current installed-artifact evidence on both supported desktop platforms",
        positive="Independently install and smoke-test release artifacts on Windows and Linux",
        negative="Prepare mobile application-store metadata and staged rollout settings",
        negative_rationale="A mobile release specialist owns application-store delivery",
        authority="review",
        relationship_target="cross-platform-installer-engineer",
    ),
    _definition(
        "selection-safety-critic",
        "Selection Safety Critic",
        "Independent criticism of proposed workforce selection and composition",
        outcomes=["Unsafe selections rejected", "Selection tradeoffs made explicit"],
        artifacts=["Selection safety verdict", "Candidate comparison evidence"],
        capabilities=[
            "Coverage challenge",
            "Forbidden-candidate detection",
            "Margin challenge",
            "Lifecycle and near-neighbor analysis",
        ],
        anti=["Primary recruitment", "Work implementation", "Agent prompt modification"],
        phases=["planning", "review"],
        tools=["workforce-index", "staffing-plan-reader"],
        closest="code-reviewer",
        insufficiency="Reviews source changes rather than workforce-selection correctness",
        differentiation="Challenges coverage, forbidden candidates, weak margins, lifecycle errors, and dangerous near neighbors",
        positive="Critique a staffing proposal with a weak margin and a clinically specialized near-neighbor",
        negative="Review a TypeScript source diff for correctness and maintainability",
        negative_rationale="A code reviewer owns source-diff review",
        authority="review",
    ),
)

KNOWN_CONTRACTOR_CONTRACTS: tuple[EmploymentContract, ...] = tuple(
    parse_employment_contract(item) for item in _RAW_DEFINITIONS
)
KNOWN_CONTRACTORS_BY_SLUG = {item.slug: item for item in KNOWN_CONTRACTOR_CONTRACTS}

__all__ = ["KNOWN_CONTRACTORS_BY_SLUG", "KNOWN_CONTRACTOR_CONTRACTS"]
