"""Agent host installer — detect, wire, and toggle Agency Runtime adapters.

Supports: Hermes, OpenClaw, Codex, Claude Code.

Each host gets a thin plugin file that imports from the installed
agency_runtime package. The plugin file is the on/off toggle point.
"""

from __future__ import annotations

import os
import shutil
from pathlib import Path
from typing import Any

from agency_runtime.core.config import AgencyConfig
from agency_runtime.core.policy.defaults import STARTER_ROSTER
from agency_runtime.core.store.sqlite import Store


# ── Host definitions ──────────────────────────────────────────

# Each host's plugin directory and detection method
HOSTS: dict[str, dict[str, Any]] = {
    "hermes": {
        "plugin_dir": "~/.hermes-nexus/plugins/agency-preflight",
        "detect_paths": ["~/.hermes-nexus", "~/.hermes-nexus/plugins"],
        "detect_binary": "hermes",
    },
    "openclaw": {
        "plugin_dir": "~/.openclaw/agency-preflight",
        "detect_paths": ["~/.openclaw"],
        "detect_binary": None,  # OpenClaw may not have a standalone binary
    },
    "codex": {
        "plugin_dir": "~/.codex/agency-preflight",
        "detect_paths": ["~/.codex"],
        "detect_binary": "codex",
    },
    "claude": {
        "plugin_dir": "~/.claude/agency-preflight",
        "detect_paths": ["~/.claude"],
        "detect_binary": "claude",
    },
}


# ── Plugin template ───────────────────────────────────────────

_PLUGIN_TEMPLATE = '''"""Agency Runtime — {host} plugin (auto-installed).

This file was generated by `agency install --agent {host}`.
It imports the installed agency_runtime package and wires host hooks.

To disable: `agency off --agent {host}` (renames this file to .disabled)
To re-enable: `agency on --agent {host}`
To remove: delete this directory.
"""

import logging

from agency_runtime.adapters.{host_module}.plugin import {adapter_class}
from agency_runtime.core.config import load_config

logger = logging.getLogger("plugins.agency_preflight")

_adapter: {adapter_class} | None = None


def _get_adapter() -> {adapter_class}:
    global _adapter
    if _adapter is None:
        _adapter = {adapter_class}()
    return _adapter


def register(ctx):
    """Register Agency Runtime hooks with {host}."""
    ctx.register_hook("pre_llm_call", _on_pre_llm_call)
    ctx.register_hook("pre_verify", _on_pre_verify)
    ctx.register_hook("post_tool_call", _on_post_tool_call)
    ctx.register_hook("post_api_request", _on_post_api_request)
    ctx.register_hook("transform_llm_output", _on_transform_llm_output)

    adapter = _get_adapter()
    catalog = adapter.store.get_active_roster_as_catalog()
    config = load_config()
    logger.info(
        "agency-runtime: {adapter_class} wired — %d agents in roster",
        len(catalog),
    )


def _on_pre_llm_call(**kwargs):
    return _get_adapter().pre_llm_call_handler(
        session_id=kwargs.get("session_id") or "",
        user_message=kwargs.get("user_message") or "",
        model=kwargs.get("model") or "",
    )


def _on_pre_verify(**kwargs):
    return _get_adapter().pre_verify_handler(
        final_response=kwargs.get("final_response") or "",
        session_id=kwargs.get("session_id") or "",
        model=kwargs.get("model") or "",
        attempt=kwargs.get("attempt") or 0,
    )


def _on_post_tool_call(**kwargs):
    _get_adapter().post_tool_call_handler(**kwargs)


def _on_post_api_request(**kwargs):
    _get_adapter().post_api_request_handler(**kwargs)


def _on_transform_llm_output(**kwargs):
    return _get_adapter().apply_finalization(
        kwargs.get("response_text") or "",
        kwargs.get("session_id") or "",
        kwargs.get("model") or "",
    )
'''

# Host module/class mappings
_HOST_ADAPTER_MAP = {
    "hermes": {"host_module": "hermes", "adapter_class": "HermesAdapter"},
    "openclaw": {"host_module": "openclaw", "adapter_class": "OpenClawAdapter"},
    "codex": {"host_module": "generic", "adapter_class": "GenericAdapter"},
    "claude": {"host_module": "generic", "adapter_class": "GenericAdapter"},
}


# ── Detection ─────────────────────────────────────────────────


def detect_installed_agents() -> list[str]:
    """Detect which AI agent hosts are installed on this machine."""
    detected: list[str] = []
    for host_name, host_info in HOSTS.items():
        if _is_host_installed(host_name, host_info):
            detected.append(host_name)
    return detected


def _is_host_installed(host_name: str, host_info: dict[str, Any]) -> bool:
    """Check if a specific host is installed."""
    # Check paths
    for path_template in host_info.get("detect_paths", []):
        path = Path(os.path.expanduser(path_template))
        if path.exists():
            return True
    # Check binary
    binary = host_info.get("detect_binary")
    if binary and shutil.which(binary):
        return True
    return False


# ── Install ───────────────────────────────────────────────────


def install_agent_adapter(host: str, cfg: AgencyConfig | None = None) -> dict[str, Any]:
    """Write the plugin file for a specific agent host.

    Returns {"ok": True, "plugin_path": str} or {"ok": False, "error": str}.
    """
    if host not in HOSTS:
        return {"ok": False, "error": f"Unknown host: {host}. Supported: {', '.join(HOSTS)}"}

    host_info = HOSTS[host]
    plugin_dir = Path(os.path.expanduser(host_info["plugin_dir"]))

    # Verify host is actually installed
    if not _is_host_installed(host, host_info):
        return {"ok": False, "error": f"{host} is not installed on this machine"}

    # Create plugin directory
    plugin_dir.mkdir(parents=True, exist_ok=True)

    # Write __init__.py
    adapter_map = _HOST_ADAPTER_MAP.get(host, _HOST_ADAPTER_MAP["codex"])
    plugin_content = _PLUGIN_TEMPLATE.format(
        host=host,
        host_module=adapter_map["host_module"],
        adapter_class=adapter_map["adapter_class"],
    )

    init_path = plugin_dir / "__init__.py"
    init_path.write_text(plugin_content)

    # Remove any .disabled marker
    disabled_path = plugin_dir / "__init__.py.disabled"
    if disabled_path.exists():
        disabled_path.unlink()

    return {
        "ok": True,
        "plugin_path": str(init_path),
        "host": host,
    }


# ── Toggle (on/off) ───────────────────────────────────────────


def toggle_agency(host: str, enabled: bool) -> dict[str, Any]:
    """Enable or disable Agency Runtime for a host.

    On disable: renames __init__.py → __init__.py.disabled
    On enable: renames __init__.py.disabled → __init__.py
    """
    if host not in HOSTS:
        return {"ok": False, "error": f"Unknown host: {host}"}

    host_info = HOSTS[host]
    plugin_dir = Path(os.path.expanduser(host_info["plugin_dir"]))
    active_path = plugin_dir / "__init__.py"
    disabled_path = plugin_dir / "__init__.py.disabled"

    if enabled:
        # Check if disabled file exists
        if disabled_path.exists():
            shutil.move(str(disabled_path), str(active_path))
            return {"ok": True, "action": "enabled"}
        elif active_path.exists():
            # Already enabled
            return {"ok": True, "action": "already_enabled"}
        else:
            # Need to install fresh
            return install_agent_adapter(host)
    else:
        # Disable: rename active to disabled
        if active_path.exists():
            shutil.move(str(active_path), str(disabled_path))
            return {"ok": True, "action": "disabled", "backup_path": str(disabled_path)}
        elif disabled_path.exists():
            return {"ok": True, "action": "already_disabled"}
        else:
            return {"ok": False, "error": f"No plugin found for {host}. Run: agency install --agent {host}"}


# ── Roster seeding ────────────────────────────────────────────


def seed_starter_roster(store: Store) -> int:
    """Seed the starter roster into the store."""
    count = 0
    for agent in STARTER_ROSTER:
        store.activate_agent(dict(agent))
        count += 1
    store.record_import_event("starter_roster_installed", "", f"count={count}")
    return count


__all__ = [
    "HOSTS",
    "detect_installed_agents",
    "install_agent_adapter",
    "toggle_agency",
    "seed_starter_roster",
]
