"""Agent host installer — detect, wire, and toggle Agency Runtime adapters.

Supports: Hermes, OpenClaw, Codex, Claude Code.

Each host gets a thin plugin file that imports from the installed
agency_runtime package. The plugin file is the on/off toggle point.
"""

from __future__ import annotations

import os
import shutil
from pathlib import Path
from typing import Any

from agency_runtime.core.config import AgencyConfig
from agency_runtime.core.policy.defaults import STARTER_ROSTER
from agency_runtime.core.store.sqlite import Store


# ── Host definitions ──────────────────────────────────────────

# Each host's plugin directory and detection method
HOSTS: dict[str, dict[str, Any]] = {
    "hermes": {
        "plugin_dir": "~/.hermes-nexus/plugins/agency-preflight",
        "detect_paths": ["~/.hermes-nexus", "~/.hermes-nexus/plugins"],
        "detect_binary": "hermes",
    },
    "openclaw": {
        "plugin_dir": "~/.openclaw/plugins/agency-preflight",
        "detect_paths": ["~/.openclaw"],
        "detect_binary": None,  # OpenClaw may not have a standalone binary
    },
    "codex": {
        "plugin_dir": "~/.codex/agency-preflight",
        "detect_paths": ["~/.codex"],
        "detect_binary": "codex",
    },
    "claude": {
        "plugin_dir": "~/.claude/agency-preflight",
        "detect_paths": ["~/.claude"],
        "detect_binary": "claude",
    },
}


# ── Plugin templates ──────────────────────────────────────────

_PYTHON_PLUGIN_TEMPLATE = '''"""Agency Runtime — {host} plugin (auto-installed).

This file was generated by `agency install --agent {host}`.
It imports the installed agency_runtime package and wires host hooks.

To disable: `agency off --agent {host}` (renames this file to .disabled)
To re-enable: `agency on --agent {host}`
To remove: delete this directory.
"""

import logging
import sys
from pathlib import Path

_PACKAGE_ROOT = Path("{package_root}")
if str(_PACKAGE_ROOT) not in sys.path:
    sys.path.insert(0, str(_PACKAGE_ROOT))

from agency_runtime.adapters.{adapter_module} import {adapter_class}

logger = logging.getLogger("plugins.agency_preflight")

_adapter: {adapter_class} | None = None


def _get_adapter() -> {adapter_class}:
    global _adapter
    if _adapter is None:
        _adapter = {adapter_class}()
    return _adapter


def register(ctx):
    """Register Agency Runtime hooks with {host}."""
    ctx.register_hook("pre_llm_call", _on_pre_llm_call)
    ctx.register_hook("pre_verify", _on_pre_verify)
    ctx.register_hook("post_tool_call", _on_post_tool_call)
    ctx.register_hook("post_api_request", _on_post_api_request)
    ctx.register_hook("transform_llm_output", _on_transform_llm_output)

    adapter = _get_adapter()
    catalog = adapter.store.get_active_roster_as_catalog()
    logger.info(
        "agency-runtime: {adapter_class} wired — %d agents in roster",
        len(catalog),
    )


def _on_pre_llm_call(**kwargs):
    return _get_adapter().pre_llm_call_handler(
        session_id=kwargs.get("session_id") or "",
        user_message=kwargs.get("user_message") or "",
        model=kwargs.get("model") or "",
    )


def _on_pre_verify(**kwargs):
    return _get_adapter().pre_verify_handler(
        final_response=kwargs.get("final_response") or "",
        session_id=kwargs.get("session_id") or "",
        model=kwargs.get("model") or "",
        attempt=kwargs.get("attempt") or 0,
    )


def _on_post_tool_call(**kwargs):
    _get_adapter().post_tool_call_handler(**kwargs)


def _on_post_api_request(**kwargs):
    _get_adapter().post_api_request_handler(**kwargs)


def _on_transform_llm_output(**kwargs):
    return _get_adapter().apply_finalization(
        kwargs.get("response_text") or "",
        kwargs.get("session_id") or "",
        kwargs.get("model") or "",
    )
'''

_OPENCLAW_PACKAGE_JSON = '''{
  "type": "module",
  "private": true,
  "openclaw": {
    "extensions": ["./index.js"]
  }
}
'''

_OPENCLAW_MANIFEST_JSON = '''{
  "id": "agency-preflight",
  "name": "Agency Preflight",
  "description": "Injects Agency Runtime specialist routing context and enforces Agency headers.",
  "activation": {
    "onStartup": true,
    "onCapabilities": ["hook"]
  },
  "configSchema": {
    "type": "object",
    "additionalProperties": false
  }
}
'''

_OPENCLAW_INDEX_JS = '''import {{ definePluginEntry }} from "openclaw/plugin-sdk/plugin-entry";
import {{ spawnSync }} from "node:child_process";

const PYTHON = process.env.AGENCY_RUNTIME_PYTHON || "/usr/bin/python3";
const PACKAGE_ROOT = "{package_root}";

function runBridge(payload) {{
  const env = {{ ...process.env, PYTHONPATH: [PACKAGE_ROOT, process.env.PYTHONPATH].filter(Boolean).join(":") }};
  const result = spawnSync(PYTHON, ["-m", "agency_runtime.adapters.openclaw.node_bridge"], {{
    input: JSON.stringify(payload),
    encoding: "utf8",
    maxBuffer: 1024 * 1024,
    env,
  }});
  if (result.status !== 0) {{
    throw new Error((result.stderr || result.stdout || `agency bridge exited ${{result.status}}`).trim());
  }}
  return JSON.parse(result.stdout || "{{}}");
}}

function sessionId(event, ctx) {{
  return String(ctx?.sessionKey || ctx?.sessionId || event?.sessionKey || event?.sessionId || "");
}}

function modelId(ctx) {{
  return String(ctx?.modelId || ctx?.activeModel?.modelId || ctx?.model || "");
}}

function textFromMessage(message) {{
  const content = message?.content ?? message?.text ?? message?.message;
  if (typeof content === "string") return content;
  if (Array.isArray(content)) {{
    return content.map((part) => typeof part === "string" ? part : String(part?.text || "")).join("\\n").trim();
  }}
  return "";
}}

function userPrompt(event) {{
  const prompt = typeof event?.prompt === "string" ? event.prompt : "";
  if (prompt.trim() && prompt.length < 4000) return prompt;
  const messages = Array.isArray(event?.messages) ? event.messages : [];
  for (let i = messages.length - 1; i >= 0; i -= 1) {{
    const role = String(messages[i]?.role || messages[i]?.type || "").toLowerCase();
    if (role.includes("user")) {{
      const text = textFromMessage(messages[i]);
      if (text) return text;
    }}
  }}
  return prompt;
}}

function finalAssistantText(event) {{
  return String(
    event?.lastAssistantMessage ||
    event?.finalAssistantText ||
    event?.assistantText ||
    event?.text ||
    ""
  );
}}

export default definePluginEntry({{
  id: "agency-preflight",
  name: "Agency Preflight",
  description: "Injects Agency Runtime specialist routing context and enforces Agency headers.",
  register(api) {{
    api.on("before_prompt_build", async (event, ctx) => {{
      const routed = runBridge({{
        action: "preflight",
        sessionId: sessionId(event, ctx),
        userMessage: userPrompt(event),
        model: modelId(ctx),
      }});
      return routed.context ? {{ appendContext: routed.context }} : undefined;
    }}, {{ priority: 100 }});

    api.on("before_agent_finalize", async (event, ctx) => {{
      const decision = runBridge({{
        action: "pre_verify",
        sessionId: sessionId(event, ctx),
        finalResponse: finalAssistantText(event),
        model: modelId(ctx),
        attempt: 0,
      }});
      if (decision.action !== "continue") return undefined;
      return {{
        action: "revise",
        reason: decision.message,
        retry: {{
          instruction: decision.message,
          idempotencyKey: "agency-preflight-header",
          maxAttempts: 2,
        }},
      }};
    }}, {{ priority: 100 }});

    api.logger.info?.("agency-runtime: OpenClaw agency-preflight hooks registered");
  }},
}});
'''


_HOST_ADAPTER_MAP = {
    "hermes": {"host_module": "hermes.plugin", "adapter_class": "HermesAdapter"},
    "openclaw": {"host_module": "openclaw.plugin", "adapter_class": "OpenClawAdapter"},
    "codex": {"host_module": "codex.wrapper", "adapter_class": "CodexAdapter"},
    "claude": {"host_module": "claude.wrapper", "adapter_class": "ClaudeAdapter"},
}


# ── Detection ─────────────────────────────────────────────────


def _host_path(path_template: str, *, home_dir: str | Path | None = None) -> Path:
    """Resolve a host path, optionally pinning ``~`` to an explicit home.

    Tests and smoke checks must pass ``home_dir`` so platform-specific home
    discovery can never redirect writes into the operator's real profile.
    """
    if home_dir is not None:
        home = Path(home_dir).resolve()
        if path_template == "~":
            return home
        if path_template.startswith(("~/", "~\\")):
            candidate = (home / path_template[2:]).resolve()
            if not candidate.is_relative_to(home):
                raise ValueError(f"host path escapes explicit home boundary: {path_template}")
            return candidate
    return Path(os.path.expanduser(path_template))


def detect_installed_agents(*, home_dir: str | Path | None = None) -> list[str]:
    """Detect which AI agent hosts are installed on this machine."""
    detected: list[str] = []
    for host_name, host_info in HOSTS.items():
        if _is_host_installed(host_name, host_info, home_dir=home_dir):
            detected.append(host_name)
    return detected


def _is_host_installed(
    host_name: str,
    host_info: dict[str, Any],
    *,
    home_dir: str | Path | None = None,
) -> bool:
    """Check if a specific host is installed."""
    # Check paths
    for path_template in host_info.get("detect_paths", []):
        path = _host_path(path_template, home_dir=home_dir)
        if path.exists():
            return True
    # Check binary
    binary = host_info.get("detect_binary")
    if binary and shutil.which(binary):
        return True
    return False


# ── Install ───────────────────────────────────────────────────


def install_agent_adapter(
    host: str,
    cfg: AgencyConfig | None = None,
    *,
    home_dir: str | Path | None = None,
) -> dict[str, Any]:
    """Write the plugin file for a specific agent host.

    Returns {"ok": True, "plugin_path": str} or {"ok": False, "error": str}.
    """
    if host not in HOSTS:
        return {"ok": False, "error": f"Unknown host: {host}. Supported: {', '.join(HOSTS)}"}

    host_info = HOSTS[host]
    plugin_dir = _host_path(host_info["plugin_dir"], home_dir=home_dir)

    # Verify host is actually installed
    if not _is_host_installed(host, host_info, home_dir=home_dir):
        return {"ok": False, "error": f"{host} is not installed on this machine"}

    # Create plugin directory
    plugin_dir.mkdir(parents=True, exist_ok=True)

    # Write __init__.py
    adapter_map = _HOST_ADAPTER_MAP.get(host, _HOST_ADAPTER_MAP["codex"])
    if host == "openclaw":
        package_root = Path(__file__).resolve().parents[2]
        plugin_path = plugin_dir / "index.js"
        plugin_path.write_text(
            _OPENCLAW_INDEX_JS.format(package_root=package_root.as_posix()),
            encoding="utf-8",
        )
        (plugin_dir / "openclaw.plugin.json").write_text(
            _OPENCLAW_MANIFEST_JSON,
            encoding="utf-8",
        )
        (plugin_dir / "package.json").write_text(
            _OPENCLAW_PACKAGE_JSON,
            encoding="utf-8",
        )
        return {
            "ok": True,
            "plugin_path": str(plugin_path),
            "host": host,
        }

    plugin_content = _PYTHON_PLUGIN_TEMPLATE.format(
        host=host,
        adapter_module=adapter_map["host_module"],
        adapter_class=adapter_map["adapter_class"],
        package_root=Path(__file__).resolve().parents[2].as_posix(),
    )

    init_path = plugin_dir / "__init__.py"
    init_path.write_text(plugin_content, encoding="utf-8")

    # Write plugin.yaml manifest so the host plugin loader discovers us.
    # Without this Hermes logs "Skipping 'agency-preflight' (no manifest)".
    manifest_path = plugin_dir / "plugin.yaml"
    manifest_path.write_text(
        "name: agency-preflight\n"
        "version: 0.1.0\n"
        "description: Agency Runtime specialist preflight, delegation tracking, and header enforcement.\n"
        "provides_hooks:\n"
        "  - pre_llm_call\n"
        "  - pre_verify\n"
        "  - post_tool_call\n"
        "  - post_api_request\n"
        "  - transform_llm_output\n",
        encoding="utf-8",
    )

    # Remove any .disabled marker
    disabled_path = plugin_dir / "__init__.py.disabled"
    if disabled_path.exists():
        disabled_path.unlink()

    return {
        "ok": True,
        "plugin_path": str(init_path),
        "host": host,
    }


# ── Toggle (on/off) ───────────────────────────────────────────


def toggle_agency(
    host: str,
    enabled: bool,
    *,
    home_dir: str | Path | None = None,
) -> dict[str, Any]:
    """Enable or disable Agency Runtime for a host.

    On disable: renames __init__.py → __init__.py.disabled
    On enable: renames __init__.py.disabled → __init__.py
    """
    if host not in HOSTS:
        return {"ok": False, "error": f"Unknown host: {host}"}

    host_info = HOSTS[host]
    plugin_dir = _host_path(host_info["plugin_dir"], home_dir=home_dir)
    active_path = plugin_dir / "__init__.py"
    disabled_path = plugin_dir / "__init__.py.disabled"

    if enabled:
        # Check if disabled file exists
        if disabled_path.exists():
            shutil.move(str(disabled_path), str(active_path))
            return {"ok": True, "action": "enabled"}
        elif active_path.exists():
            # Already enabled
            return {"ok": True, "action": "already_enabled"}
        else:
            # Need to install fresh
            return install_agent_adapter(host, home_dir=home_dir)
    else:
        # Disable: rename active to disabled
        if active_path.exists():
            shutil.move(str(active_path), str(disabled_path))
            return {"ok": True, "action": "disabled", "backup_path": str(disabled_path)}
        elif disabled_path.exists():
            return {"ok": True, "action": "already_disabled"}
        else:
            return {"ok": False, "error": f"No plugin found for {host}. Run: agency install --agent {host}"}


# ── Roster seeding ────────────────────────────────────────────


def seed_starter_roster(store: Store) -> int:
    """Seed bundled starter agents without overwriting a synced active roster."""
    existing_slugs = {agent.get("agent_slug") for agent in store.get_active_roster()}
    count = 0
    for agent in STARTER_ROSTER:
        if agent["slug"] in existing_slugs:
            continue
        store.activate_agent(dict(agent))
        count += 1
    store.record_import_event("starter_roster_installed", "", f"count={count}")
    return count


__all__ = [
    "HOSTS",
    "detect_installed_agents",
    "install_agent_adapter",
    "toggle_agency",
    "seed_starter_roster",
]
